### ISSUE TITLE
haproxy interface not working properly in Safari after 18.7 update

### ISSUE THREAD

**Issue by digitalcohesion** [opnsense/plugins#770]
I can no longer edit certain fields in the haproxy interface after updating to 18.7 using Safari. It seems there is some piece of javascript that safari is having problems with.

One example is the listen addresses field on the public service form. That field appears larger than it should and clicking in it does nothing nor can I type in it.

Checking errors in the developer tools it's complaining about an undefined function in some way on line 215 of opnsense_ui.js.

`$tokenizer = $(this).tokenize({`

Error is:
undefined is not a function (near '...$(this).tokenize...')

I didn't experience this issue on the previous version.

![screen shot 2018-08-01 at 9 02 44 am](https://user-images.githubusercontent.com/4694328/43526385-b99cbaa6-9569-11e8-8ff8-5359f16fabb1.png)

**Comment by fichtner** [comment]
Can you clear your browser cache / use a different browser to test?

**Comment by digitalcohesion** [comment]
I tried it on another computer which has never logged in to opnsense before and it does seem to behave like Firefox and Chrome did with the odd menu up in the left corner of the screen. I still can't seem to click on into the field, but maybe this is really the same issue as #769.

I'll have to try the fix there and report back...

The fix seems to work, but not perfectly. I have to click in and out of the listen addresses field or tab in and out of it before I can type anything. Something is still a little strange, but not sure what's the cause. 

In any case, I think this issue can be closed or merged with the other one, whichever is more appropriate.
